package com.memoforward.blog.mapper;

import com.memoforward.blog.model.BlogWithType;
import com.memoforward.blog.model.BlogWithTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BlogWithTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    long countByExample(BlogWithTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    int deleteByExample(BlogWithTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    int insert(BlogWithType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    int insertSelective(BlogWithType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    List<BlogWithType> selectByExampleWithRowbounds(BlogWithTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    List<BlogWithType> selectByExample(BlogWithTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    BlogWithType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") BlogWithType record, @Param("example") BlogWithTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    int updateByExample(@Param("record") BlogWithType record, @Param("example") BlogWithTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    int updateByPrimaryKeySelective(BlogWithType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    int updateByPrimaryKey(BlogWithType record);
}