package com.memoforward.blog.model;

public class BlogWithTags {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_tags.id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_tags.blog_id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private Long blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_tags.tag_id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private Long tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_tags.id
     *
     * @return the value of t_blog_tags.id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_tags.id
     *
     * @param id the value for t_blog_tags.id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_tags.blog_id
     *
     * @return the value of t_blog_tags.blog_id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_tags.blog_id
     *
     * @param blogId the value for t_blog_tags.blog_id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_tags.tag_id
     *
     * @return the value of t_blog_tags.tag_id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_tags.tag_id
     *
     * @param tagId the value for t_blog_tags.tag_id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }
}