package com.memoforward.blog.model;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.title
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.pic_url
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.mark
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.view_count
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private Long viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.show_appreciation
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private String showAppreciation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.show_comment
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private String showComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.show_statement
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private String showStatement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.is_published
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private String isPublished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.create_time
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.modified_time
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private Long modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.type_id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private Long typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.user_id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.is_recommended
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private String isRecommended;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.tag_ids
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private String tagIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.description
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.content
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.id
     *
     * @return the value of t_blog.id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.id
     *
     * @param id the value for t_blog.id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.title
     *
     * @return the value of t_blog.title
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.title
     *
     * @param title the value for t_blog.title
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.pic_url
     *
     * @return the value of t_blog.pic_url
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.pic_url
     *
     * @param picUrl the value for t_blog.pic_url
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.mark
     *
     * @return the value of t_blog.mark
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.mark
     *
     * @param mark the value for t_blog.mark
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.view_count
     *
     * @return the value of t_blog.view_count
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public Long getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.view_count
     *
     * @param viewCount the value for t_blog.view_count
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.show_appreciation
     *
     * @return the value of t_blog.show_appreciation
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public String getShowAppreciation() {
        return showAppreciation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.show_appreciation
     *
     * @param showAppreciation the value for t_blog.show_appreciation
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setShowAppreciation(String showAppreciation) {
        this.showAppreciation = showAppreciation == null ? null : showAppreciation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.show_comment
     *
     * @return the value of t_blog.show_comment
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public String getShowComment() {
        return showComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.show_comment
     *
     * @param showComment the value for t_blog.show_comment
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setShowComment(String showComment) {
        this.showComment = showComment == null ? null : showComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.show_statement
     *
     * @return the value of t_blog.show_statement
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public String getShowStatement() {
        return showStatement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.show_statement
     *
     * @param showStatement the value for t_blog.show_statement
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setShowStatement(String showStatement) {
        this.showStatement = showStatement == null ? null : showStatement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.is_published
     *
     * @return the value of t_blog.is_published
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public String getIsPublished() {
        return isPublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.is_published
     *
     * @param isPublished the value for t_blog.is_published
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setIsPublished(String isPublished) {
        this.isPublished = isPublished == null ? null : isPublished.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.create_time
     *
     * @return the value of t_blog.create_time
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.create_time
     *
     * @param createTime the value for t_blog.create_time
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.modified_time
     *
     * @return the value of t_blog.modified_time
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public Long getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.modified_time
     *
     * @param modifiedTime the value for t_blog.modified_time
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setModifiedTime(Long modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.type_id
     *
     * @return the value of t_blog.type_id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.type_id
     *
     * @param typeId the value for t_blog.type_id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.user_id
     *
     * @return the value of t_blog.user_id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.user_id
     *
     * @param userId the value for t_blog.user_id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.is_recommended
     *
     * @return the value of t_blog.is_recommended
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public String getIsRecommended() {
        return isRecommended;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.is_recommended
     *
     * @param isRecommended the value for t_blog.is_recommended
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setIsRecommended(String isRecommended) {
        this.isRecommended = isRecommended == null ? null : isRecommended.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.tag_ids
     *
     * @return the value of t_blog.tag_ids
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public String getTagIds() {
        return tagIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.tag_ids
     *
     * @param tagIds the value for t_blog.tag_ids
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setTagIds(String tagIds) {
        this.tagIds = tagIds == null ? null : tagIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.description
     *
     * @return the value of t_blog.description
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.description
     *
     * @param description the value for t_blog.description
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.content
     *
     * @return the value of t_blog.content
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.content
     *
     * @param content the value for t_blog.content
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    @Override
    public String toString() {
        return "Blog{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", picUrl='" + picUrl + '\'' +
                ", mark='" + mark + '\'' +
                ", viewCount=" + viewCount +
                ", showAppreciation='" + showAppreciation + '\'' +
                ", showComment='" + showComment + '\'' +
                ", showStatement='" + showStatement + '\'' +
                ", isPublished='" + isPublished + '\'' +
                ", createTime=" + createTime +
                ", modifiedTime=" + modifiedTime +
                ", typeId=" + typeId +
                ", userId=" + userId +
                ", isRecommended='" + isRecommended + '\'' +
                ", tagIds='" + tagIds + '\'' +
                ", description='" + description + '\'' +
                ", content='" + content + '\'' +
                '}';
    }
}