package com.memoforward.blog.model;

public class Type {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.name
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.id
     *
     * @return the value of t_type.id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.id
     *
     * @param id the value for t_type.id
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.name
     *
     * @return the value of t_type.name
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.name
     *
     * @param name the value for t_type.name
     *
     * @mbg.generated Thu Apr 16 14:53:23 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}